version: '3'
services:
  frontend:
    image: 578568968001.dkr.ecr.us-east-1.amazonaws.com/flarestack_frontend:latest
    # restart: always
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    #@ extra_hosts:
    #  - host.docker.internal:host-gateway
  backend:
    image: 578568968001.dkr.ecr.us-east-1.amazonaws.com/flarestack_backend:latest
    # restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    ##extra_hosts:
    #  - host.docker.internal:host-gateway
    environment:
      #- DATABASE_CONNECTION=mongodb://mongo:27017/dev1
      - DATABASE_CONNECTION=mongodb+srv://sandbox_admin:secret123@sandbox.ohaxk.mongodb.net/flarestack_development2?retryWrites=true&w=majority
      - DATABASE_TRANSACTIONS=false
      - FRONTEND_URL=http://localhost
      - FRONTEND_URL_WITH_SUBDOMAIN=http://[subdomain].localhost
      - BACKEND_URL=http://localhost:8080/api
      - FILE_STORAGE_PROVIDER=aws
      - FILE_STORAGE_BUCKET=flarestack-dev
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIA3MK2MQT2HKPSOKOD
      - AWS_SECRET_ACCESS_KEY=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
      - AUTH_SOCIAL_GOOGLE_CLIENT_ID=605635252608-phm991alk5dicbqq6rnji74sjmqkcdq7.apps.googleusercontent.com
      - AUTH_SOCIAL_GOOGLE_CLIENT_SECRET=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
      - AUTH_SOCIAL_GOOGLE_CALLBACK_URL=http://localhost:8080/api/auth/social/google/callback
      - AUTH_JWT_SECRET=dskklklklfjewos
      - AUTH_JWT_EXPIRES_IN=7 days
      - API_DOCUMENTATION_ENABLED=true
      - TENANT_MODE=single
  mongo:
    image: mongo:4
    profiles:
      - dev
    ports:
      - 27017:27017
    extra_hosts:
      - host.docker.internal:host-gateway
