version: '3'
services:
  frontend:
    image: flarestack_frontend
    container_name: frontend
    networks:
      - ai_net
    build:
      context: ./frontend
      dockerfile: Dockerfile
  backend:
    image: flarestack_backend
    container_name: backend
    networks:
      - ai_net
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./env/backend.env

networks:
  ai_net:
